# Generated by Django 3.2 on 2022-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longi',
        ),
        migrations.AddField(
            model_name='place',
            name='addr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
